### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by rikinogues** [hypecal/wordpress-events-manager-tickets-payments#3]
Hi,
I´ve problems with your plugin, when I´m istalling it, I have followed all your indications, install de 2 plugins (Events Manager, and Event MAnager EES) but when I´m going to activate the Hypecal Ticketing System, I´ve got an error.

My error log is like this:
PHP Fatal error:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required 

Could you help me on that?

Thanks in advance

**Comment by safarjaisur** [comment]
Hi   My friend    I  am  also  gone  through this kind of issue like 

Warning: require_once(N:\home\hhandswp\www\wp-content\plugins\events-manager-tickets-payments\inc\config/libs/HC_HTTP.php) [function.require-once]: failed to open stream: No such file or directory in N:\home\hhandswp\www\wp-content\plugins\events-manager-tickets-payments\inc\config\HC_Config.php on line 15

Solution Of : 
change  the  path at  wordpress-events-manager-tickets-payments-master\inc\config\HC_Config.php 
file change  the $dir  variable  replace with this constant  EM_HYPECAL_DIR.'/inc.  

For  example : 
Before :require_once( $dir .'libs/HC_HTTP.php' );
after:require_once(EM_HYPECAL_DIR. '/inc/libs/HC_HTTP.php' );

Do it this  for  all
issue  will  be  resolved and  What  you  Want  :)

**Comment by superbibi** [comment]
Hi Safar,
Thanks for your suggestion, it makes sense.
I have placed the global EM_HYPECAL_DIR variable as the folder name to include the files and this should solve the problem on specific server configuration.
