### ISSUE TITLE
The bank account owner name is mandatory.

### ISSUE THREAD

**Issue by Papik81** [hypecal/wordpress-events-manager-tickets-payments#4]
No matter how hard I try, I cannot fill in the bank account owner name field. If I fill the entire form, it is not saved telling "The bank account owner name is mandatory.". Issue on Wordpress 4.1.

**Comment by BricePissard** [comment]
The issue is solved. 
We use the same API for several implementation of our ticketing service. An update made on the https://www.hypecal.com have created this error.
thanks for your comment.
