### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by Rikdegraaf** [hypecal/wordpress-events-manager-tickets-payments#6]
Hi there,
I would really like to use this plugin, but after installing it gives me te following error:

Warning: preg_match_all() expects at least 3 parameters, 2 given in /home/grapefish/domains/projects.grapefish.nl/public_html/develop/wp-content/plugins/events-manager-tickets-payments/inc/models/HC_IO.php on line 40

I know this has something to do with the PHP version our server is on which is 5.3.29.
But we are on shared hosting and can't update.

So I tried update that rule by passing an extra parameter. Which works initially, but then I get another error.
On the step "Sync your events with Hypecal.com" I can click on sync now and it opens the authorization popup. I login and click yes to authorize. 

It transports me back to the booking page still on the second step. So I can't get it to authorize.

Is there any solution to this problem?

**Comment by superbibi** [comment]
I Rick,
I've fixed the 3rd param for the preg_match_all with a PHP version < 5.3. for the next release.
I can see that two accounts have been created with two different emails.
For now the plugin version of Hypecal only support one email per account.
I have placed an auto-logout if the synchronization is refused.
Can you try to login and sync again within your Wordpress admin section, to see if it works fine now?

Thanks.

**Comment by Rikdegraaf** [comment]
Hi superbibi,
I tried, but it didn't work. Maybe my replacement in HC_IO.php is wrong?

Should I do something about settings or something else to make sure it works?

**Comment by superbibi** [comment]
They were an update on the OAuth2 transfer protocol that was not correctly posted on the previous release. 
I just finished the checking and submitted a new release on Wordpress.
You should be able now to unsync and resync your Wordpress website with different Hypecal account.
Could you come back to me here to tell me if it works on your side?

Thanks

**Comment by Rikdegraaf** [comment]
I can sync now! So that is good.
But how do I create tickets for events, because I tested it and I get this error message:

"This event doesn't seem to belong to this account. Please log in."
I can create custom tickets, but I can't seem to create tickets for the events in event manager because I get the error message as stated above.

**Comment by superbibi** [comment]
Once your events are saved the data is submit to cloud servers. 
We are working on publishing your tickets automatically to other portals to increase the point of sales.  
The instant replication, the cache and the security controls could produce this issue. 
We did an update on our servers to prevent this.
Could you tell me if you arrived to make a complete workflow from creating a ticket to simulate a payment ?

Thanks

**Comment by Rikdegraaf** [comment]
Allright bibi all is working now!

Thanks for the your outstanding efforts!
