### ISSUE TITLE
Error message while adding tickets

### ISSUE THREAD

**Issue by mpek** [hypecal/wordpress-events-manager-tickets-payments#8]
In Admin area an error message appears when adding and saving ticket(s):

DataTables warning: table id=edit-event-prices-grid - Requested unknown parameter '7' for row 0. For more information about this error, please see http://datatables.net/tn/4

Screenshot:
![events-manager-hypecal_datatables_warning](https://cloud.githubusercontent.com/assets/6974695/15994076/0c512d44-30fa-11e6-9ca4-0f6ae2767500.PNG)

WordPress is in german language.
Site URL:
http://pekic.de/eventsmanager

**Comment by BricePissard** [comment]
Hi, sorry for the delay.
The problem is fixed. it should work fine now.
